### ISSUE TITLE
Styles still perform poorly with modern getpocket.com

### ISSUE THREAD

**Issue by lukewlms** [StylishThemes/Pocket-Dark#3]
Looks like the style is performing poorly on getpocket.com.  Does this need to be updated or deprecated a la the Netflix version?

Thanks!

* **Browser**: FF
* **Operating System**: Mac OS
* **Link to page with the issue**: https://getpocket.com/a/queue/list/
* **Screenshot**:
![Screen Shot 2019-05-24 at 15 00 43](https://user-images.githubusercontent.com/19214773/58347717-f4aeb400-7e34-11e9-9fba-c9165a008083.png)

**Comment by the-j0k3r** [comment]
Hello @lukewlms, thank you for reaching out with this report.

This theme has no maintainer since 2014, the only update(s) [were recently](https://github.com/StylishThemes/Pocket-Dark/pulls?q=is%3Apr+is%3Aclosed) by @AfroThundr3007730, so the answer is likely it needs to be updated.

I unfortunately dont use this theme or even pocket, but if anyone wants to update it, please go ahead.
Im sure we would consider adding someone to maintain this theme.to the team @Mottie @silverwind can decide on that too.Thanks.

**Comment by the-j0k3r** [comment]
I also suggest installing the user.css style, it will automatically update as fixes are added and releases are made.

**Comment by the-j0k3r** [comment]
possible fix impending https://github.com/StylishThemes/Pocket-Dark/pull/4

This style needs a considerable amount of updates to get it to spec, so all help that anyone interested can provide, will be greatly appreciated =)
